service: dio-serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:GetItem
          - dynamodb:scan
        Resource:
          - arn:aws:dynamodb:us-east-1:011143853159:table/ItemTableNew

functions:
  api:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get
  insertItem:
    handler: src/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  getitem:
    handler: src/getitem.handler
    events:
      - http:
          path: /item
          method: get
  fetchitem:
    handler: src/fetchitem.handler
    events:
      - http:
          path: /item/{id}
          method: get
  updateitem:
    handler: src/updateitem.handler
    events:
      - http:
          path: /item/{id}
          method: put


resources:
  Resources:
    ItemTableNew:
    Type: AWS::DynamoDB::Tabel
    Properties:
      TableName: ItemTableNew
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH     